services:
    Asdoria\SyliusConfiguratorPlugin\Controller\Shop\AddToCartController:
        public: true
        arguments:
            $twig: '@twig'
            $formFactory: '@form.factory'
            $configuratorAddToCartCommandFactory: '@Asdoria\SyliusConfiguratorPlugin\Factory\ConfiguratorAddToCartCommandFactory'
            $validator: '@validator'
            $urlGenerator: '@sylius.router.checkout_state'
            $orderModifier: '@sylius.order_modifier'
            $cartManager: '@sylius.manager.order'
            $restViewHandler: '@fos_rest.view_handler'
            $cartContext: '@sylius.context.cart.new'
            $validationGroups: '%sylius.form.type.order_item.validation_groups%'
