asdoria_shop_product_configurator:
    resource: "routes/shop.yaml"
    prefix: /{_locale}/%asdoria_product_configurator.path_shop_name%/
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

asdoria_admin_product_configurator:
    resource: "routes/admin.yaml"
    prefix: /%sylius_admin.path_name%
