asdoria_admin_ajax_product_attribute_by_code:
    path: /leaf
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete, Default]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]

asdoria_admin_ajax_product_attribute_by_name_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete, Default]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: expr:service('request_stack').getCurrentRequest().query.get('phrase', '')
                    locale: null
                    limit: 25
